name: Continuous Integration

on:
  pull_request:
    branches: ["main", "release"]
  workflow_dispatch:

env:
  JAVA_OPTS: -Xms512m -Xmx1024m
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  # Removed the following options as they are supported only in Java 11
  # -XX:MaxPermSize=2048m

jobs:
  build_artifacts:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      # Uncomment if the repo is public - doesn't work for private GitHub repos
      # - name: Bundle build report
      #   if: always()
      #   run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      # - name: Upload build report
      #   if: always()
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: error-report
      #     path: build-reports.zip

      # - name: Bundle analysis report
      #   if: always()
      #   run: mkdir sarif && find . -name '*.sarif' | xargs -I{} cp "{}" ./sarif/

      # - name: Upload analysis report
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: sarif