name: Build documentation (no publish)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Generate Dokka documentation
        run: ./gradlew processDokkaDocs
      - uses: actions/setup-node@v3
        with:
          path: website
          node-version: 18
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: website

      - name: Build website
        run: npm run build
        working-directory: website
